### ISSUE TITLE
Parallel on syntax

### ISSUE THREAD

**Issue by DanielVoogsgerd** [epi-project/brane-documentation#28]
In the Brane syntax definition there is a parallel `On` syntax that is not fully worked out. I also cannot find something on it in the documenation. Is this a planned feature that was never documented, or is a bit of the spec missing? 

https://github.com/epi-project/brane-documentation/blob/e52e52f1bdf1b8a01c741d01488f0ccf283b8e42/specification/src/appendix/languages/bscript/syntax.md?plain=1#L78

**Comment by Lut99** [comment]
Ah! No it's a mix between legacy on-blocks and the new attributes which I've never added. Good catch. I'll whip up a PR for it in a moment.
