### ISSUE TITLE
Idea: Move compilation instructions to separate page, rustdoc, or readme.md

### ISSUE THREAD

**Issue by DanielVoogsgerd** [epi-project/brane-documentation#4]
A lot of binaries can be either installed by downloading them via branectl or by compiling them from source. I think instructions on compilation are valuable, but maybe not necessarilly in full inside the user-guide. I think there is a better space for these instructions, namely, in the readme for the workspace members. So compilation instructions for brane-api can go in `brane-api/readme.md`.

I think we can still link to them from the user-guide, but this might make the user-guide seem a lot less daunting. I am of course also open to other ideas.

@Lut99 Curious what you think.

**Comment by Lut99** [comment]
Created a PR (#8) with an attempt. What do you think?
